function hk_government_covid_cases_in_mainland_china = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  HK_GOVERNMENT_COVID_CASES_IN_MAINLAND_CHINA = IMPORTFILE(FILENAME)
%  reads data from text file FILENAME for the default selection.
%  Returns the data as a table.
%
%  HK_GOVERNMENT_COVID_CASES_IN_MAINLAND_CHINA = IMPORTFILE(FILE,
%  DATALINES) reads data for the specified row interval(s) of text file
%  FILENAME. Specify DATALINES as a positive scalar integer or a N-by-2
%  array of positive scalar integers for dis-contiguous row intervals.
%
%  Example:
%  hk_government_covid_cases_in_mainland_china = importfile("/home/george/projects/coronavirus/latest_situation_of_reported_cases_mainland_china_eng.csv", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 05-Mar-2020 16:50:05

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 7);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Asofdate", "Asoftime", "Numberofcases", "Numberofseriouscases", "Numberofdeathcases", "Numberofcasesstillundertreatment", "Numberofdischargedcases"];
opts.VariableTypes = ["datetime", "categorical", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Asoftime", "EmptyFieldRule", "auto");
opts = setvaropts(opts, "Asofdate", "InputFormat", "dd/MM/yyyy");

% Import the data
hk_government_covid_cases_in_mainland_china = readtable(filename, opts);

end